### ISSUE TITLE
How to load plugin?

### ISSUE THREAD

**Issue by nason** [totallymoney/serverless-sns-to-sqs-events#2]
Thanks for this great plugin!

I'm having some trouble loading it in my serverless.yml, I think due to to the package's namespace.

Do you have any recommendations for how to get this loaded? I'd be happy to update the README if I could figure it out 😆

**Comment by theburningmonk** [comment]
Hi @nason I just updated the README to make it more clear, you need to reference it like this:

```
plugins:
  - "@totallymoney/serverless-sns-to-sqs-events"
```

also, we had a bug in v1.1.0 where the package.json was pointing at the wrong entry module, it should be fixed in v1.1.1 now

**Comment by nason** [comment]
Thank you! I'm able to load this plugin now
